# Project information
site_name: Burstcoin Guides
site_description: Burstcoin Guides for wallet management, mining and node operating
site_author: poc-consortium
site_url: https://github.com/poc-consortium/burstcoin-guides

# Repository
repo_name: burstcoin-guides
repo_url: https://github.com/poc-consortium/burstcoin-guides

# Theme
theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: assets/img/favicon.ico
  logo: assets/img/logo.png
  feature:
    tabs: true
  palette:
    primary: '#00579D'
    accent: '#262626'

# Options
extra:
  social:
    - type: discord
      link: https://discord.gg/q3QhyaY
    - type: github-alt
      link: https://github.com/poc-consortium
    - type: twitter
      link: https://twitter.com/burstcoin_dev

extra_css:
  - 'stylesheets/burstcoin.css'

# Page tree
pages:
  - Overview: index.md
  - Wallet:
    - Installation:
      - Windows: wallet/install/windows.md
      - Linux: wallet/install/linux.md
      - MacOS: wallet/install/macos.md
      - Docker: wallet/install/docker.md
  - Node:
    - Setup:
      - Windows: node/setup/windows.md
      - MacOS: node/setup/macos.md
      - Linux: node/setup/linux.md
  - Mining:
    - Overview: mining/overview.md
    - Plotting:
      - Windows: mining/plotting/windows.md
      - Linux: mining/plotting/linux.md
    - Mining:
      - Windows: mining/mining/windows.md
      - Linux: mining/mining/linux.md
  - Troubleshooting: troubleshoot.md

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
